version: '3'
services:
  app:
    image: golang:1.18
    container_name: rate-limiter-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - rate-limiter-network

  redis:
    image: redis:6.2
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network

networks:
  rate-limiter-network:
    driver: bridge
