services:
  api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-rest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - rate-limiter-network
    volumes:
      - ./.env:/app/.env 
      
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning

networks:
  rate-limiter-network:
    driver: bridge
